name: darter
description: A simple task runner.
version: 0.0.1
repository: https://github.com/kentt8046/darter

environment:
  sdk: ^3.1.0

dependencies:
  args: ^2.4.2
  glob: ^2.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  darter:
